version: "3.7"

services:
  wdb:
    image: kozea/wdb:3.3.0
    ports: ["1984:1984"]
    networks:
      - odoonet
    depends_on: ["db"]

  # ------------------------

  odoo:
    # user: odoo
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # Host paths (addons & conf)
      - ./.devcontainer/.vscode:/etc/.vscode
    environment:
      - WDB_SOCKET_SERVER=wdb
      - WDB_NO_BROWSER_AUTO_OPEN=True
      - WDB_WEB_PORT=1984
    command: ["odoo", "--dev", "wdb,reload,qweb,werkzeug,xml"]
    depends_on: ["db", "wdb"]
