version: "3.7"

networks:
  default:
    external:
      name: cloudbuild
  odoonet:

volumes:
  odoo-data:
  odoo-config:
  odoo-testlogs:
  psql:

services:
  odoo:
    image: iterativodo/dockerdoo:12.0
    environment:
      # Libraries version
      WKHTMLTOX_VERSION: ${WKHTMLTOX_VERSION}
      WKHTMLTOPDF_CHECKSUM: ${WKHTMLTOPDF_CHECKSUM}
      NODE_VERSION: ${NODE_VERSION}
      BOOTSTRAP_VERSION: ${BOOTSTRAP_VERSION}

    ports: ["8069:8069", "8072:8072"]

    volumes:
      # Host paths (addons & conf)
      - ./custom:/mnt/extra-addons
      # Named volumes
      - odoo-config:/etc/odoo
      - odoo-data:/var/lib/odoo/data
      - odoo-testlogs:/var/lib/odoo/logs

    depends_on:
      - db

    networks:
      odoonet:
  # ------------------------
  db:
    image: postgres:${PSQL_VERSION:-11}
    restart: unless-stopped
    volumes:
      - psql:/var/lib/postgresql/data/pgdata
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-odoo}
      - POSTGRES_USER=${POSTGRES_USER:-odoo}
      - PGDATA=/var/lib/postgresql/data/pgdata

    networks:
      odoonet:
